config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  resources :users, only: [:show]
  resources :thumbnails, only: [:new]
  resources :posts, except: [:show] do
    member do 
      post 'upvote'
      post 'fupvote'
    end
  end

  post 'posts/fview' => 'posts#fview'
  post 'posts/view'  => 'posts#view'
  post 'posts/validate' => 'posts#validate'
  get 'posts/unpin' => 'posts#unpin'
  get 'posts/reset_future_posts' => 'posts#reset_future_posts'



  authenticated :user do 
    root "posts#index"
  end

  root 'static_pages#home'
  get '/about',    to: 'static_pages#about'
  get '/datenschutz',   to: 'static_pages#datenschutz'
  get '/nutzung', to: 'static_pages#nutzung'
  get '/impressum', to: 'static_pages#impressum'
  get '*path' => redirect('/')
end

app/views/layouts/_carousel.html.erb
<% if current_user.group == 0 || current_user.group == 1 %>
  <i class="fa fa-arrow-circle-left btn prev arrows" aria-hidden="true"></i>
<% end %>

<div class="col-md-12 middle-carousel">

<div id="owl-carousel">

  <% if current_user.group == 0 || current_user.group == 1 %>
    <% @pinned.each do |post| %>
      <div>
        <% if post.is_a?(Post) %>
          <%= render :partial => "layouts/index-preview-bubble", :locals => {:post => post} %> 
        <% else %>
          <%= render :partial => "layouts/index_preview_fposts", :locals => {:post => post} %>  
        <% end %>
      </div>
    <% end %>
  <% else %>
    <% @random_fposts.each do |post| %>
      <div>
        <% if post.is_a?(Post) %>
          <%= render :partial => "layouts/index-preview-bubble", :locals => {:post => post} %> 
        <% else %>
          <%= render :partial => "layouts/index_preview_fposts", :locals => {:post => post} %>  
        <% end %>
      </div>
    <% end %>

  <% end %>

  </div>

</div>

<% if current_user.group == 0 || current_user.group == 1 %>
  <i class="fa fa-arrow-circle-right btn next arrows" aria-hidden="true"></i>
<% end %>








<!--  
<div class="customNavigation">
  <a class="btn prev">< Vorheriges</a>
  <a class="btn next">Nächstes ></a>
</div>

-->


<script type="text/javascript">
    $(document).ready(function(){
    	  //var owl = $("#owl-carousel");

        //owl.trigger('refresh.owl.carousel');

        var $owl = $("#owl-carousel").owlCarousel({
           	slideSpeed: 300,
           	paginationSpeed: 400,
            <% if current_user.group == 2 || current_user.group == 3 %>
              <%= "autoPlay: 8000," %>
            <% end %>
           	items: 3,
            nav: true,
            loop: true,
            rewindNav: false,
            navText: [
              "<i class='fa fa-chevron-left'></i>",
              "<i class='fa fa-chevron-right'></i>"
            ],
        });

        $owl.trigger('refresh.owl.carousel');

        // Custom navigation events

        $(".next").click(function(){
        	$owl.trigger('owl.next');
        })
        $(".prev").click(function(){
        	$owl.trigger('owl.prev');
        })

    });
</script>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <span class="flash-message"><%= message %></span>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container footer-text">
    <small>
      Heroku AG Copyright 2017
    </small>
    <nav>
      <ul>
        <li><%= link_to "Über uns", about_path %></li>
        <li><%= link_to "Datenschutz", datenschutz_path %></li>
        <li><%= link_to "Nutzungsbedingungen", nutzung_path %></li>
        <li><%= link_to "Impressum", impressum_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container header-text">
        <%= link_to root_path, class: "logo" do %>
          <span class="fa fa-paper-plane header-logo" aria-hidden="true"></span> Heroku
        <% end %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="" data-toggle="dropdown" class="dropdown-toggle bell">
                  <i class="fa fa-bell" aria-hidden="true"></i>
                </a>
                <ul class="dropdown-menu no-notification">
                  <li class="nix">Keine Benachrichtigungen</li>
                </ul>
                <ul class="dropdown-menu notifications">
                  <li class="notifications"> <%= link_to "Jemand hat einen neuen Beitrag erstellt (1)", posts_path(anchor: "anchor") %></li>
                </ul>
              </li>

              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Menü <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to new_post_path, id: "new-post", data: {toggle: "modal", target: "#my-modal", :remote => true} do %>
                      <span class="fa fa-paper-plane" area-hidden="true"></span> Neuer Beitrag
                    <% end %>

                  </li>

                  <li class="divider"></li>

                  <li><%= link_to "Alle Beiträge", posts_path %></li>
                  <li><%= link_to "Meine Beiträge", current_user %></li>

                  <li class="divider"></li>
                  
                  <li>
                    <%= link_to edit_user_registration_path do %>
                      <span class="fa fa-cog" aria-hidden="true"></span>  Einstellungen
                    <% end %>
                  </li>


                  <li class="divider"></li>

                  <li>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                      <span class="fa fa-sign-out" aria-hidden="true"></span>  Ausloggen
                    <% end %>
                  </li>
                </ul>
              </li>
              <li>
                <%= link_to destroy_user_session_path, class: "logout", method: :delete do %>
                  <span class="fa fa-sign-out" aria-hidden="true"></span>  Ausloggen
                <% end %>
              </li>


            <% else %>
              <li><%= link_to 'Einloggen', new_user_session_path %></li>
              <li><%= link_to 'Registrieren', new_user_registration_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_index-preview-bubble.html.erb
<% if post %>

	  <div class="time-and-likes">

	  	<% heroku_timezone = post.created_at %>

	  	<div class="time"><%= time_ago_in_words(heroku_timezone) %></div>

	  	<div class="trash icons">
			<% if (post.user_id == current_user.id) %>
				<%= link_to "Löschen", post_path(post), method: :delete, data: { confirm: "Bist du sicher, dass du diesen Beitrag löschen möchtest?" } %>
				<i class="fa fa-trash-o" aria-hidden="true"></i>
			<% end %>
		</div>

	  	<div class="views icons">
	  	
	  		<span class="counter view-<%=post.id%>"> 

	  		  <% num_of_user_views = post.views.where(user_id: current_user).size %>

		  	  <% if current_user.group == 0 || current_user.group == 2 %>
		  	    <%= num_of_user_views ? post.highviews + num_of_user_views : post.highviews %>
		  	  <% else %>
		  	    <%= num_of_user_views ? post.lowviews + num_of_user_views : post.lowviews %>
		  	  <% end %>

	  		</span>
	  	

	  		<i class="fa fa-eye eye-<%=post.id%>" aria-hidden="true"></i>	
	  	</div>


	  	<div class="likes icons">
	  		<span class="counter like-<%=post.id%>"> 
	  		  <% num_of_user_likes = post.likes.where(user_id: current_user).size %>

		  	  <% if current_user.group == 0 || current_user.group == 2 %>
		  	    <%= num_of_user_likes ? post.highlikes + num_of_user_likes : post.highlikes %>
		  	  <% else %>
		  	    <%= num_of_user_likes ? post.lowlikes + num_of_user_likes : post.lowlikes %>
		  	  <% end %>
	  		</span>
	  		
	  		<%= link_to upvote_post_path(post), method: :post, class: "heart", remote: true do %>
	  		  <% if post.likes.where(user_id: current_user).empty? %>
	  		  	<i class="fa fa-heart-o heart-<%=post.id%>" aria-hidden="true"></i>	
	  		  <% else %>
	  		  	<i class="fa fa-heart heart-<%=post.id%>" aria-hidden="true"></i>	
	  		  <% end %>
	  		<% end %>
	  	</div>
	  </div>


	<% preview = LinkThumbnailer.generate(post.link, image_stats: false, verify_ssl: false) %>

	  <div class="index-preview">
	    <!--<%= link_to content_tag(:span), post.link, target: "_blank" %>-->
		<div class="image-text">

		  <% if (current_user.group == 0 || current_user.group == 1) && post.pinned %>
		  	<i class="fa fa-thumb-tack" aria-hidden="true"></i>
		  <% end %>
		  
		  <% if !preview.images.first.nil? %>
		  	<%= link_to(image_tag(preview.images.first.src.to_s), post.link, class: "link", id: post.id, target: "_blank") %> 
		  <% end %>
		  <h4 class="text"><%= link_to preview.title, post.link, class: "link", id: post.id,target: "_blank" %></h4>
		</div>

		<% if (current_user.group == 0 || current_user.group == 1) && post.pinned %>
		  <div class="pinned comment">
		<% else %>
	      <div class="comment">
		<% end %>
    	  <div class="avatar">
		    <%= image_tag post.user.avatar.url %>
		  </div>

		  <p class="curator-comment">
		    Kurator/in <%= post.user.first_name %> <%= post.user.last_name %>: 
		    <span class="more"><%= post.description %></span>	
		  </p>
		</div>
	  </div> 
	 

	 <!--
	 <% if post.pinned %>
		<%= link_to "Beitrag entpinnen?",posts_unpin_path, class: "unpin", :data => {:confirm => "Bist du sicher, dass du deinen Beitrag entpinnen möchtest? "} %>
	 <% end %>
	 -->
<% end %>

app/views/layouts/_index_preview_fposts.html.erb
<% if post %>

	  <div class="time-and-likes">

	  	<% heroku_timezone = DateTime.parse(post.fake_time.to_s).localtime %>

	  	<% if heroku_timezone.future? %>
	  		<div class="time time-<%=post.id%>">vor weniger als einer Minute</div>
	  	<% else %>
	  		<div class="time time-<%=post.id%>"><%= time_ago_in_words(heroku_timezone) %></div>
	  	<% end %>


	  	<div class="views icons">

	  		<% if heroku_timezone.future? %>
	  			<span class="counter view-<%=post.id%>">0</span>
	  		<% else %>
		  		<span class="counter view-<%=post.id%>"> 
		  		  <% num_of_user_views = post.fviews.where(user_id: current_user).size %>

			  	  <% if current_user.group == 0 || current_user.group == 2 %>
			  	    <%= num_of_user_views ? post.highviews + num_of_user_views : post.highviews %>
			  	  <% else %>
			  	    <%= num_of_user_views ? post.lowviews + num_of_user_views : post.lowviews %>
			  	  <% end %>
		  		</span>
	  		<% end %>

	  		<i class="fa fa-eye eye-<%=post.id%>" aria-hidden="true"></i>	

	  	</div>

		<div class="likes icons">

		<% if heroku_timezone.future? %>
	  		<span class="counter like-<%=post.id%>">0</span>
		<% else %>
	  		<span class="counter like-<%=post.id%>"> 
	  		  <% num_of_user_likes = post.flikes.where(user_id: current_user).size %>

		  	  <% if current_user.group == 0 || current_user.group == 2 %>
		  	    <%= num_of_user_likes ? post.highlikes + num_of_user_likes : post.highlikes %>
		  	  <% else %>
		  	    <%= num_of_user_likes ? post.lowlikes + num_of_user_likes : post.lowlikes %>
		  	  <% end %>
	  		</span>
		<% end %>



			
	  		<%= link_to fupvote_post_path(post), method: :post, class: "heart", remote: true do %>
	  		  <% if post.flikes.where(user_id: current_user).empty? %>
	  		  	<i class="fa fa-heart-o heart-<%=post.id%>" aria-hidden="true"></i>	
	  		  <% else %>
	  		  	<i class="fa fa-heart heart-<%=post.id%>" aria-hidden="true"></i>	
	  		  <% end %>
	  		<% end %>
	  	
	  	</div>
	  </div>


	  <div class="index-preview">
	    <!--<%= link_to content_tag(:span), post.link, target: "_blank" %>-->
		<div class="image-text">

		  <% if (current_user.group == 0 || current_user.group == 1) && post.pinned %>
		  	<i class="fa fa-thumb-tack" aria-hidden="true"></i>
		  <% end %>


		  <%= link_to(image_tag(post.image_url, class: "cover"), post.link, class: "flink", id: post.id, target: "_blank") %> 
		  <h4 class="text" id="view-<%= post.id%>">
		  	<%= link_to post.title, post.link, class: "flink", id: post.id, target: "_blank" %>
		  </h4>
		</div>

		<% if (current_user.group == 0 || current_user.group == 1) && post.pinned %>
		  <div class="pinned comment">
		<% else %>
	      <div class="comment">
		<% end %>

    	  <div class="avatar">
		    <%= image_tag (post.picture) %>
		  </div>
		  <p class="curator-comment">
		    Kurator/in <%= post.first_name %> <%= post.last_name %>: 
		    <span class="more"><%= post.description %></span>	
		  </p>
		</div>
	  </div> 

<% end %>

app/views/layouts/_new-post-modal.html.erb
<div class="modal fade" id="my-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/layouts/_preview-bubble.html.erb
      <% preview = LinkThumbnailer.generate(post.link) %>
      <div class="bubble linkpreview">
        <% if post.pinned %>
          <i class="fa fa-thumb-tack icon" aria-hidden="true"></i>
        <% else %>
          <%= image_tag "image_icon.svg", class: "icon" %>  
        <% end %>
        <div class="preview">
          <%= link_to(image_tag(preview.images.first.src.to_s), post.link) %> 
        </div>   
        <div class="content content-<%=post.pinned%>">
          <h2 class="title"><%= preview.title %></h2>
          <p class="description"><%=  preview.description %></p>
          <div class="buttons_wrapper">
            <%= link_to "Zum Artikel", post.link, target: "_blank", class: "btn btn-primary" %>
            <% if post.user_id == current_user.id %>
              <%= link_to "Editieren", edit_post_path(post) %>
            <% end %>
          </div>
        </div>       
      </div>

      <div class="bubble">
        <div class="content content-<%=post.pinned%>">
          <div class="avatar">
            <%= image_tag "avatar.png" %>
          </div>
          <p class="copy"><span class="kurator">Kurator <%= post.user.username %> sagt:</span> <%= post.description %></p>
        </div>
        <p class="time"><%= post.created_at.strftime("%d %b. %Y")%> - <%= post.created_at.strftime("%H:%M Uhr") %></p>
      </div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/_sidebar.html.erb
    <div id="sidebar-wrapper">
    	<div class="avatar_info">
        <%= image_tag current_user.avatar.url %>
    	  Hallo <%= current_user.username %>!
    	</div>

    	<hr>

    	<div class="readers">
    	  <h4>Anzahl Leser auf Sharit:</h4>
    	  <p>134</p>
    	</div>

    	<hr>
    	<div class="others">
    	  <h4>Andere Kuratoren:</h4>
    	  <div class="other_avatars">

      	  	<%= link_to(image_tag("user_generic.png"), "#") %>
      	  	<%= link_to(image_tag("user_generic.png"), "#") %>
    	  	  <%= link_to(image_tag("ngoc_avatar.jpg"), "#") %>
       	  	<%= link_to(image_tag("user_generic.png"), "#") %>
       	  	<%= link_to(image_tag("user_generic.png"), "#") %>
       	  	<%= link_to(image_tag("avatar_client.png"), "#") %>
       	  	<%= link_to(image_tag("user_generic.png"), "#") %>
       	  	<%= link_to(image_tag("avatar.png"), "#") %>      	  	
    	  </div>
    	</div>
    </div>

app/views/layouts/_statistics.html.erb
<% if user_signed_in? %>

<div class="statistics">
  <div class="container header-text">
    <div class="col-md-6 personal">
      <%= image_tag current_user.avatar.url %>
      <span class="stats-small personal-stats">
        Hallo <%= current_user.first_name %>! Du bist Kurator.
      </span>
    </div>

    <div class="col-md-6 personal sharit-stats">

      <!--
      <span class="stats-small">
        <% if current_user.group == 0 || current_user.group == 2 %>
          Leser (heute): <%= current_user.highreaders %>
        <% else %>
          Leser (heute): <%= current_user.lowreaders %>
        <% end %>
      <span>
      -->
    </div>

  </div>
</div>

<% end %>

app/views/layouts/_user-sidebar.html.erb
    <div id="sidebar-wrapper">
    	<div class="avatar_info">
        <%= image_tag current_user.avatar.url %>
    	</div>

    	<hr>

    	<div class="readers">
    	  <h4>Dein Profil, <%= @user.first_name %> <%= @user.last_name %>!</h4>
    	  <p>Hier findest du all deine Beiträge und Favoriten</p>
          <p> Beiträge: <%= @user.posts.size %> </p>
          <% if current_user.group == 0 || current_user.group == 1 %>
            <p> Angepinnte Beiträge: <%= @user.posts.where(pinned: true).size %></p>
          <% end %>
          <p> Favoriten: <%= @likes.size %></p>
    	</div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "home" if controller_name == "home" %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Das sollte nur geladen werden für die "new" Page 
      <script src="http://timemejs.com/timeme.min.js"></script>
    -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:300" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"> 
    <%= render 'layouts/shim' %>
  </head>
  
  <% if action_name === "home" %>
    <body class="body_home">
      <% flash.each do |type, message| %>
        <div class="home-alert alert <%= bootstrap_class_for(type) %> fade in">
          <button class="close" data-dismiss="alert">×</button>
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
  <% else %>
    <body>

      <%= render 'layouts/new-post-modal' %>
      <%= render 'layouts/header' %>
      <%= render 'layouts/statistics' %>
      <%= render partial: "layouts/flash", flash: flash %> 


      <div class="container main-content">
        <%= yield %>
      </div>

      <%= render 'layouts/footer' %>

  <% end %>
    </body>
</html>